### ISSUE TITLE
Disconnecting

### ISSUE THREAD

**Issue by sickidolderivative** [magcode/mpower-tools#11]
Let me start by thanking you for the really great work. Your solution makes my mPower PRO integrate smoothly with my Home Assistant instance. 

One thing I noticed is that instead on maintaining continuous connection to Mosquitto server, my mPower constantly connects and disconnects to the Mosquitto server every second. It reads commands and posts states as it should, but by connecting and disconnecting so frequently it floods my HA logs. 

Is connecting and disconnecting the desired behaviour? Is there a way to make mPower maintain constant connection to the Mosquitto server?

**Comment by magcode** [comment]
Thanks for trying and giving feedback.

See https://github.com/magcode/mpower-tools/issues/10#issuecomment-450618913
