### ISSUE TITLE
Problems with number of ports on mPower Pro

### ISSUE THREAD

**Issue by wizmo2** [magcode/mpower-tools#13]
Firstly, thanks for this.  top rate 

Have been testing with home-assistant and mosquitto on a hass.io platform.  Everything works great except if doesn't get the number of ports right on my mPowerPro P8U.  
For know I have hard-coded the PORTS value in the mqrun script and it sems to work

Here is the board.inc
 
$board_id="0xe648";
$board_name="mPower Pro";
$board_raw_name="mPower Pro";
$board_shortname="P8U";
$board_subtype="";
$board_hwaddr="F09FC246AAEE";
$reboot_time=30;
$upgrade_time=150;
$radio_count=1;
$radio1_name="";
$radio1_shortname="";
$radio1_bus="ahb";
$radio1_ccode=840;
$radio1_ccode_locked=0;
$radio1_subsystemid="0xe648";
$radio1_subvendorid="0x0777";
$radio1_txpower_max=23;
$radio1_txpower_offset=5;
$radio1_low_txpower_atten=0;
$radio1_low_txpower_limit=0;
$radio1_ieee_modes=10;
$radio1_ieee_mode="11nght";
$radio1_ant_count=1;
$radio1_def_antenna=4;
$radio1_ant_id[0]=4;
$radio1_ant_name[0]=dict_translate("Combined");
$radio1_ant_gain[0]=0;
$radio1_ant_builtin[0]=1;
$radio1_caps=16404;
$radio1_distance_limit_km=0;
$radio1_chains=2;
$radio1_ieee_mode_bg=1;
$radio1_low_txpower_mode=0;
$radio1_legacy=0;
$radio_outdoor=0;
$feature_advanced_ethernet=1;
$feature_poe_passthrough=0;
$feature_advanced_ethernet_phy=1;
$feature_rssi_leds=0;
$feature_power=1;

Not much use except for the shortname

perhaps the easiest solution would be do add something to the mpower-pub.cfg to override

**Comment by magcode** [comment]
Yeah. That's strange. 
I have 3 different (EU mpower's: 1,3,6 ports. All of them have the correct value in "feature_power".

I guess it would be safe to use "board_shortname".
I commited a change. Want to try?
