### ISSUE TITLE
mPower - Read-only file system

### ISSUE THREAD

**Issue by Basicek1** [magcode/mpower-tools#15]
Good day,
could I ask you for advice? I am trying to install MQTT server, unfortunately with the following error:
Thank you for your help.

MF.v2.1.11# sh install-client.sh
Installing mPower MQTT v2 ...
/libmosquitto.so.1: Read-only file system
/mosquitto_pub: Read-only file system
/mosquitto_sub: Read-only file system
mkdir: cannot create directory '/client': Read-only file system
find: /client: No such file or directory
/client/mqrun.sh: No such file or directory
/client/mqpub-static.sh: No such file or directory
/client/mqpub.sh: No such file or directory
/client/mqsub.sh: No such file or directory
/client/mqstop.sh: No such file or directory
/client/mpower-pub.cfg: No such file or directory
/client/mqtt.cfg: No such file or directory
/client/led.cfg: No such file or directory
chmod: /mosquitto_pub: No such file or directory
chmod: /mosquitto_sub: No such file or directory
chmod: /client/mqrun.sh: No such file or directory
chmod: /client/mqpub-static.sh: No such file or directory
chmod: /client/mqpub.sh: No such file or directory
chmod: /client/mqsub.sh: No such file or directory
chmod: /client/mqstop.sh: No such file or directory
Found /etc/persistent/rc.poststart entry. File will not be changed
Done!
Please configure mqtt.cfg
Please configure mpower-pub.cfg
Please configure led.cfg
run 'save' command if done.

**Comment by mdonke** [comment]
That is very strange!

could you please execute some commands manually?

```
LOCALDIR="/var/etc/persistent/mqtt"
echo "my localdir is $LOCALDIR"
ls -la $localdir
```

also please post the contents of your (downloaded) install-client.sh

**Comment by magcode** [comment]
That is very strange!

could you please execute some commands manually?

```
LOCALDIR="/var/etc/persistent/mqtt"
echo "my localdir is $LOCALDIR"
ls -la $localdir
```

also please post the contents of your (downloaded) install-client.sh

**Comment by Basicek1** [comment]
Thank you for the answer, I immediately tried:

MF.v2.1.11# LOCALDIR="/var/etc/persistent/mqtt"
MF.v2.1.11# echo "my localdir is $LOCALDIR"
my localdir is /var/etc/persistent/mqtt
MF.v2.1.11# ls -la $localdir
drwxrwxrwx    2 admin    admin          60 Jan  1  1970 .
drwxr-xr-x    7 admin    admin         160 Jan  1  1970 ..
-rwxr-xr-x    1 admin    admin        3106 Mar 31 09:01 install-client.sh
MF.v2.1.11#

**Comment by magcode** [comment]
please do a `cat install-client.sh` and post the output

**Comment by Basicek1** [comment]
I copied content from install-client.sh and saved in to mPower via the "vi" editor:

#!/bin/sh

LOCALDIR="/var/etc/persistent/mqtt"
LOCALSCRIPTDIR=$LOCALDIR/client
BASEURL="https://raw.githubusercontent.com/magcode/mpower-tools/master/mqtt"

echo "Installing mPower MQTT v2 ..."
wget --no-check-certificate -q $BASEURL/libmosquitto.so.1?raw=true -O $LOCALDIR/libmosquitto.so.1
wget --no-check-certificate -q $BASEURL/mosquitto_pub?raw=true -O $LOCALDIR/mosquitto_pub
wget --no-check-certificate -q $BASEURL/mosquitto_sub?raw=true -O $LOCALDIR/mosquitto_sub
mkdir -p $LOCALSCRIPTDIR
# clean directory, but leave *.cfg files untouched
find $LOCALSCRIPTDIR ! -name '*.cfg' -type f -exec rm -f '{}' \;
wget --no-check-certificate -q $BASEURL/client/mqrun.sh -O $LOCALSCRIPTDIR/mqrun.sh
wget --no-check-certificate -q $BASEURL/client/mqpub-static.sh -O $LOCALSCRIPTDIR/mqpub-static.sh
wget --no-check-certificate -q $BASEURL/client/mqpub.sh -O $LOCALSCRIPTDIR/mqpub.sh
wget --no-check-certificate -q $BASEURL/client/mqsub.sh -O $LOCALSCRIPTDIR/mqsub.sh
wget --no-check-certificate -q $BASEURL/client/mqstop.sh -O $LOCALSCRIPTDIR/mqstop.sh

if [ ! -f $LOCALSCRIPTDIR/mpower-pub.cfg ]; then
    wget --no-check-certificate -q $BASEURL/client/mpower-pub.cfg -O $LOCALSCRIPTDIR/mpower-pub.cfg
fi

if [ ! -f $LOCALSCRIPTDIR/mqtt.cfg ]; then
    wget --no-check-certificate -q $BASEURL/client/mqtt.cfg -O $LOCALSCRIPTDIR/mqtt.cfg
fi

if [ ! -f $LOCALSCRIPTDIR/led.cfg ]; then
    wget --no-check-certificate -q $BASEURL/client/led.cfg -O $LOCALSCRIPTDIR/led.cfg
fi

chmod 755 $LOCALDIR/mosquitto_pub
chmod 755 $LOCALDIR/mosquitto_sub
chmod 755 $LOCALSCRIPTDIR/mqrun.sh
chmod 755 $LOCALSCRIPTDIR/mqpub-static.sh
chmod 755 $LOCALSCRIPTDIR/mqpub.sh
chmod 755 $LOCALSCRIPTDIR/mqsub.sh
chmod 755 $LOCALSCRIPTDIR/mqstop.sh

poststart=/etc/persistent/rc.poststart
startscript="sleep 10; $LOCALSCRIPTDIR/mqrun.sh"
 
if [ ! -f $poststart ]; then
    echo "$poststart not found, creating it ..."
    touch $poststart
    echo "#!/bin/sh" >> $poststart
    chmod 755 $poststart
fi
 
if grep -q "$startscript" "$poststart"; then
   echo "Found $poststart entry. File will not be changed"
else
   echo "Adding start command to $poststart"
   echo -e "$startscript" >> $poststart
fi
 
echo "Done!"
echo "Please configure mqtt.cfg"
echo "Please configure mpower-pub.cfg"
echo "Please configure led.cfg"
echo "run 'save' command if done."

**Comment by magcode** [comment]
I'd recommend to download it using the provided script


```
wget --no-check-certificate -q https://raw.githubusercontent.com/magcode/mpower-tools/master/mqtt/client/install-client.sh -O /var/etc/persistent/mqtt/install-client.sh;
chmod 755 /var/etc/persistent/mqtt/install-client.sh;
```

**Comment by Basicek1** [comment]
I made a restart of mPower and tried the recommended:

BusyBox v1.11.2 (2015-04-06 14:24:36 PDT) built-in shell (ash)
Enter 'help' for a list of built-in commands.

MF.v2.1.11# wget --no-check-certificate -q https://raw.githubusercontent.com/mag
code/mpower-tools/master/mqtt/client/install-client.sh -O /var/etc/persistent/mq
tt/install-client.sh;
MF.v2.1.11# chmod 755 /var/etc/persistent/mqtt/install-client.sh;
MF.v2.1.11#

**Comment by magcode** [comment]
Good. Now execute the install script again!
```
/var/etc/persistent/mqtt/install-client.sh
```

**Comment by Basicek1** [comment]
if I look at install-client.sh is empty - it is zero size

MF.v2.1.11# ls
bin           data          mqtt
cfg           log           rc.poststart
MF.v2.1.11# cd mqtt
MF.v2.1.11# ls
install-client.sh
MF.v2.1.11# ls -l
-rwxr-xr-x    1 admin    admin           0 Mar 31 10:47 install-client.sh
MF.v2.1.11#

**Comment by magcode** [comment]
Your device has internet access?

Please post the output of 

```
wget --no-check-certificate https://raw.githubusercontent.com/magcode/mpower-tools/master/mqtt/client/install-client.sh -O /var/etc/persistent/mqtt/install-client.sh;
```

**Comment by Basicek1** [comment]
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=58 time=56.059 ms
64 bytes from 8.8.8.8: seq=1 ttl=58 time=13.104 ms
64 bytes from 8.8.8.8: seq=2 ttl=58 time=12.482 ms
64 bytes from 8.8.8.8: seq=3 ttl=58 time=12.426 ms
64 bytes from 8.8.8.8: seq=4 ttl=58 time=56.055 ms
^C
--- 8.8.8.8 ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 12.426/30.025/56.059 ms
MF.v2.1.11#
MF.v2.1.11# wget --no-check-certificate https://raw.githubusercontent.com/magcod
e/mpower-tools/master/mqtt/client/install-client.sh -O /var/etc/persistent/mqtt/
install-client.sh;
--2020-03-31 10:59:39--  https://raw.githubusercontent.com/magcode/mpower-tools/master/mqtt/client/install-client.sh
Resolving raw.githubusercontent.com... failed: Name or service not known.
wget: unable to resolve host address `raw.githubusercontent.com'
MF.v2.1.11#

**Comment by magcode** [comment]
Ok. That's it then. Seems like a DNS issue.
You need to fix that and afterwards you can try the installation again.

Ammended the docs:
https://github.com/magcode/mpower-tools/commit/55b43204116b5ac848df3ce62ebbbe2fb7c75645

**Comment by Basicek1** [comment]
Thank you very much for a quick response to my problem. It was really just not setting up a DNS server ...
Thank you for your project
