### ISSUE TITLE
Has anybody gathered a list of the awesome mPower/mFi repos like this one?

### ISSUE THREAD

**Issue by dragon788** [magcode/mpower-tools#16]
I stumbled on another one that helped me get connected into my mPower mini after I hadn't touched it for quite a while and forgot the alternate key exchange and cipher gotchas.

https://github.com/malensek/mpower

I ended up forking it to add in the reset-smart-bulb.sh script that I use to fix individual smart bulbs that fall out of the mesh using a desk lamp + mPower mini so that I don't have to mess with re-adding 3-4 in a ceiling fan at once, just the misbehaving one.

https://github.com/dragon788/mpower

**Comment by peturdainn** [comment]
but that is a script to run on another device to pull (poll) measurements, not something that runs on the mpower itself and pushes its readings - and it also does it for just the first port.
