### ISSUE TITLE
sh: Mini: unknown operand

### ISSUE THREAD

**Issue by Simonk007** [magcode/mpower-tools#17]
Hi,
thx for you awsome work.
when i run mqttrun.sh on my mport1 i get the following in my terminal
sh: Mini: unknown operand

what is that?
mport connects to mqtt and then disconects right away, i can't seem to figure out how to make it work. Hope you can help me out
![mqtt3](https://user-images.githubusercontent.com/5716779/102550182-b2576280-40bd-11eb-9089-0b66da383c59.png)
![mqtt](https://user-images.githubusercontent.com/5716779/102550183-b2eff900-40bd-11eb-82fe-3aa850ac109d.png)
![mqtt2](https://user-images.githubusercontent.com/5716779/102550184-b2eff900-40bd-11eb-9e37-d190e2888136.png)

**Comment by magcode** [comment]
Sorry. This tools does not yet support mport. I don't have this hardware. Feel free to implement the needed changes and create a PR.
