### ISSUE TITLE
.sh files contain ^M endine

### ISSUE THREAD

**Issue by tronto** [magcode/mpower-tools#2]
Tried installing as per direction, getting a file not found error on running mqrun.sh that mqpub.sh and mqsub.sh do not exist (they do exist). When examining the files in vi, both contain windows based ^M line breaks (as well as mqpub-static.sh) that is preventing them from running.

**Comment by magcode** [comment]
HNY!

Thanks for reporting this. Shame on me.
I changed it and it will hopefully work now.
