### ISSUE TITLE
Cloning the repository results in only empty files

### ISSUE THREAD

**Issue by spyrito79** [magcode/mpower-tools#20]
As the title suggests, it is impossible to copy the repository correctly. To partially work around this problem, you need to manually copy and paste the files.
The real problem arises when I have to copy the following files: libmosquitto.so.1, mosquitto_pub, mosquitto_sub
These being system files must necessarily be cloned as they cannot be copied and pasted as they are registry and system files.
How can I solve the problem?
Thank you

**Comment by KissmanCZ** [comment]
Because of file system limitation in latest FW version, you can download repository and copy the files manually overe SCP for example :)

**Comment by magcode** [comment]
What latest FW version are you referring to?

**Comment by spyrito79** [comment]
The last firmware i uploaded in the mFi is the 2.1.11

**Comment by spyrito79** [comment]
> Because of file system limitation in latest FW version, you can download repository and copy the files manually overe SCP for example :)

Yes, in the end i Made that with scp and works fine but my main problem remain.
It doesn’t work with openhab.

**Comment by KissmanCZ** [comment]
I did it today and it is working with Home Assistant perfectly ;)

**Comment by spyrito79** [comment]
> I did it today and it is working with Home Assistant perfectly ;)

May you send me a link how to it with home assistant please?

**Comment by spyrito79** [comment]
> > I did it today and it is working with Home Assistant perfectly ;)
> 
> May you send me a link how to do it with home assistant please?
