### ISSUE TITLE
Zero kb files

### ISSUE THREAD

**Issue by pickonedev** [magcode/mpower-tools#22]
Hi!

I am trying to install this MQTT addon to my mPower device, but when I start install-client.sh, all the files are empty.... 
Any advice?

Thank you!

**Comment by magcode** [comment]
see #21 and the documentation which says:

**Attention! Automated installation using the script below is broken at the moment. You need to copy files manually**

Install is not working. Contributions are welcome!

**Comment by pickonedev** [comment]
Oh, ok, I understand now....

And, how can I test if it is working or not, from Home Assistant? In fact, what complete topic should I choose and what payload, to publish?

I tried with topic/port1/relay/set and the payload 0 or 1 (raw), but it it not doing anything...

**Comment by pickonedev** [comment]
> see #21 and the documentation which says:
> 
> **Attention! Automated installation using the script below is broken at the moment. You need to copy files manually**
> 
> Install is not working. Contributions are welcome!

I done it, but I don't know why, after each restart of the mPower device, all the files get 0 (zero) kb again... and I have done the permissions and stuff....
