### ISSUE TITLE
MQTT reports -1 for relay state

### ISSUE THREAD

**Issue by magcode** [magcode/mpower-tools#3]
as observed by Christus https://community.ubnt.com/t5/mFi/Anybody-wants-a-MQTT-client-on-the-mPower/m-p/2230414/highlight/true#M17575

**Comment by magcode** [comment]
The value is coming directly from the mpower internals.

I guess I will just filter the value and only return "1" if mpower reports "1"

**Comment by ChristusM** [comment]
Let me know if you need help testing.

**Comment by magcode** [comment]
it's fixed now.
just run the install process again. It should leave your *.cfg untouched.

**Comment by ChristusM** [comment]
Confirmed.    Running for a couple of hours now and haven't observed any '-1' returns.   I'll watch closely for the next few days and let you know if anything changes.

Pretty sure you got it fixed.   Thank you!
