### ISSUE TITLE
Extremely usefull

### ISSUE THREAD

**Issue by Flopon** [magcode/mpower-tools#4]
Working like a charm at home, thank you !

Is it planned to add the possibility to fill in user/password to publish, and especially to receive an order from the MQTT broker?

**Comment by Flopon** [comment]
No particular use case for now, I just find more problematic to leave an MQTT actuator without authorization than a simple information flow.

I've made a pull request with an attempt to provide auth and cert option for connection to MQTT broker.

**Comment by magcode** [comment]
will close this for now. Happy to discuss further features in a new ticket.
